ERP/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('',include('user.urls',namespace="home")),
    path('hod/',include('hod.urls',namespace="hod")),
    path('staff/',include('staff.urls',namespace="staff")),
    path('student/',include('student.urls',namespace="student")),
    
   
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hod/urls.py
from django.urls import path
from .import views


app_name = "hod"

urlpatterns = [
    #session year
    path('session_year',views.SessionView.as_view(),name='session_year'),
    #login and registration
    path('admin_home',views.admin_home,name='admin_home'),
    path('register_user',views.Register.as_view(),name="register_user"),
    
    #department
    path('add_department',views.AddDepartment,name='add_department'),
    path('list_department',views.All_Department, name='list_department'),
    path('<int:pk>/delete_department',views.DepartmentDelete.as_view(),name='delete_department'),
    #course
    path('add_course',views.add_course,name='add_course'),
    path('manage_course',views.manage_course,name='manage_course'),
    path('<int:pk>/delete_course',views.CourseDelete.as_view(), name='delete_course'),
    #staff
    path('assign_staff',views.assign_staff,name='assign_staff'),
    path('manage_staff',views.manage_staff,name='manage_staff'),
    path('<int:pk>/delete_staff',views.StaffDelete.as_view(), name='delete_staff'),
    path('<pk>/update_staff',views.StaffUpdate.as_view(), name='update_staff'),
    #student
    path('enroll',views.enroll,name='enroll'),
    path('student',views.StudentView.as_view(),name='student'),
    path('manage_student',views.manage_student,name='manage_student'),
    path('<int:pk>/delete_student',views.StudentDelete.as_view(), name='delete_student'),
    path('<pk>/update_student',views.StudentUpdate.as_view(), name='update_student'),
   ]

student/urls.py
from django.urls import path
from .import views


app_name = "student"

urlpatterns = [
    path('student_home',views.student_home,name='student_home'),
    path('student_profile',views.student_profile,name='student_profile'),
]

hod/models.py
from django.db import models
from student.models import StudentProfile
from staff.models import StaffProfile
from django.contrib.auth import get_user_model
USER = get_user_model()
# Create your models here.

class SessionYearModel(models.Model):
    start = models.DateField()
    end = models.DateField()
    year= models.CharField(max_length=120)

    def __str__(self):
        return f"{self.start} {self.end}"

class Department(models.Model):
    name = models.CharField(max_length=120)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Course(models.Model):
    name = models.CharField(max_length=255)
    status = models.BooleanField(default=True)
    department = models.ForeignKey(
        Department, on_delete=models.SET_NULL, null=True, blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Staff(models.Model):
    profile = models.OneToOneField(
        StaffProfile, on_delete=models.SET_NULL, null=True, blank=True
    )
    department = models.ForeignKey(
        Department, on_delete=models.SET_NULL, null=True, blank=True
    )
    course = models.ForeignKey(
        Course, on_delete=models.SET_NULL, null=True, blank=True
    )
    user = models.OneToOneField(USER, on_delete=models.CASCADE)
    is_hod = models.BooleanField(default=False)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f"{self.user}"

class Student(models.Model):
    profile = models.OneToOneField(
        StudentProfile, on_delete=models.SET_NULL, null=True, blank=True
    )
    user = models.OneToOneField(USER, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f"{self.user}"
        
class Enroll(models.Model):
    student = models.ForeignKey(
        Student, on_delete=models.SET_NULL, null=True, blank=True
    )
    department = models.ForeignKey(
        Department, on_delete=models.SET_NULL, null=True, blank=True
    )
    session_year = models.ForeignKey(
        SessionYearModel, on_delete=models.SET_NULL, null=True, blank=True
    )
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.student}"

    

student/models.py
from django.db import models
from django.contrib.auth import get_user_model
USER = get_user_model()


# Create your models here.
class StudentLocation(models.Model):
    lattitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return f"{self.lattitude} {self.longitude}"

class StudentAddress(models.Model):
    building_name = models.CharField(max_length=64)
    place = models.CharField(max_length=64)
    street = models.CharField(max_length=64)
    city = models.CharField(max_length=64)
    district = models.CharField(max_length=64)
    state = models.CharField(max_length=64)
    country = models.CharField(max_length=64)
    post_office = models.CharField(max_length=64)
    postal_code = models.CharField(max_length=8)
    location = models.ForeignKey(
        StudentLocation, on_delete=models.SET_NULL, null=True, blank=True
    )

    def __str__(self):
        return f"{self.building_name}"

class StudentProfile(models.Model):
    MALE = "m"
    FEMALE = "f"
    LGBTQ = "lgbtq"
    GENDER_CHOICES = (
        (MALE, "Male"),
        (FEMALE, "Female"),
        (LGBTQ, "LGBTQ"),
    )
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    gender = models.CharField(max_length=15, choices=GENDER_CHOICES)
    dob = models.DateField()
    id_proof = models.FileField(upload_to="student/id_proof/", null=True, blank=True)
    image = models.ImageField(upload_to="student/profile_image/")
    address = models.ForeignKey(
        StudentAddress, on_delete=models.SET_NULL, null=True, blank=True
    )
    email = models.EmailField(max_length = 254)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

hod/forms.py
from dataclasses import fields
from xml.etree.ElementInclude import include
from django import forms
from django .forms import ModelForm
from django.contrib.auth.forms import UserCreationForm

from .models import *
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
	class Meta:
		model=User
		fields=["username","first_name","last_name","password1","email"]

class SessionYearForm(forms.ModelForm):
    class Meta:
        model=SessionYearModel
        fields='__all__'

class AddDepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        exclude = [
            "status",
            "created_on",
            "updated_on",
        ]

class AddCourseForm(ModelForm):
	class Meta:
		model=Course
		exclude = [
            "status",
            "created_at",
            "updated_at",
        ]

class StaffForm(ModelForm):
	class Meta:
		model=Staff
		fields = [
            'user',
            'department',
            'course',
        ]
        
class StudentForm(ModelForm):
	class Meta:
		model=Student
		fields = [
            'user',            
        ]
        
class EnrollForm(ModelForm):
    class Meta:
        model=Enroll
        exclude = [
            "status",
            "created_at",
            "updated_at",
        ]

student/forms.py
from django import forms
from django .forms import ModelForm
from .models import StudentProfile

class StudentProfileForm(ModelForm):
    class Meta:
        model=StudentProfile
        exclude = [
            "status",
            "created_on",
            "updated_on",
        ]

       
		
    

    

hod/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import View
from hod.forms import UserRegisterForm,AddCourseForm,StaffForm,EnrollForm,SessionYearForm,StudentForm
from django.contrib.auth.models import User
from django.views import generic as views
from django.urls import reverse_lazy
from .models import *


#homeview for Hod
def admin_home(request):
    student_count=Student.objects.all().count()
    staff_count=Staff.objects.all().count()
    course_count= Course.objects.all().count()
    department_count=Department.objects.all().count()

    return render(request,"hod/home_content.html",{'student_count':student_count," staff_count": staff_count,
    "course_count":course_count,"department_count":department_count})


class SessionView(View):
        form_class = SessionYearForm
        initial = {'key': 'value'}
        template_name = 'hod/session_year.html'

        def get(self, request, *args, **kwargs):
            form = self.form_class(initial=self.initial)
            return render(request, self.template_name, {'form': form})

        def post(self, request, *args, **kwargs):
            form = self.form_class(request.POST)
            if form.is_valid():
                form.save()
                return render(request,'hod/session_year.html')

            return render(request, self.template_name, {'form': form})

#faculty registration by HOD
class Register(View): 

    template_name='hod/register.html' 
    def get(self,request): 
        context={'form':UserRegisterForm} 
        return render(request,self.template_name,context) 
    def post(self,request): 
        username=request.POST.get('username') 
        password=request.POST.get('password1') 
        email=request.POST.get('email') 
        first_name=request.POST.get('first_name') 
        last_name=request.POST.get('last_name') 
        user=User.objects.create(username=username,
            password=password, 
            email=email, 
            first_name=first_name,
            last_name=last_name,
            is_staff=True)
        user.set_password(password)
        user.save()
        return render(request,'hod/register.html',{})
#ADD Department by HOD

def AddDepartment(request):
        if request.method == 'POST':
            if request.POST.get('name'):
                post=Department()
                post.name= request.POST.get('name')
                post.save()
                
                return render(request, 'hod/add_department.html')  

        else:
                return render(request,'hod/add_department.html')
#List all department
def All_Department(request):
    context ={}
    context["department"] = Department.objects.all()
    return render(request, 'hod/list_department.html',context)  

#Delete the department
class DepartmentDelete(views.DeleteView):
    model = Department
    template_name='hod/delete_department.html'
    success_url= reverse_lazy('hod:list_department')

#Add Course by HOD
def add_course(request):
    submitted= False
    if request.method == 'POST':
        form=AddCourseForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, "hod/add_course.html")

    else:
            form=AddCourseForm
            if 'submitted' in request.GET:
                submitted= True
            return render(request, "hod/add_course.html",{'form':form,'submitted':submitted})
    
#LIST all the courses created und each department  
def manage_course(request):
    context ={}
    context["course"] = Course.objects.all()
    return render(request, "hod/manage_course.html",context)

#Delete course by HOD
class CourseDelete(views.DeleteView):
    model = Course
    template_name='hod/delete_course.html'
    success_url= reverse_lazy('hod:manage_course')

#Assign staff to each department and course
def assign_staff(request):
    submitted= False
    if request.method == 'POST':
        form=StaffForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, "hod/assign_staff.html")

    else:
            form=StaffForm
            if 'submitted' in request.GET:
                submitted= True
            return render(request, "hod/assign_staff.html",{'form':form,'submitted':submitted})

#LIST all the staff 

def manage_staff(request):
    context ={}
    context["staff"] = Staff.objects.all()
    return render(request, "hod/manage_staff.html",context)

#Delete faculty by HOD
class StaffDelete(views.DeleteView):
    model = Staff
    template_name='hod/delete_staff.html'
    success_url= reverse_lazy('hod:manage_staff')

#update staff
class StaffUpdate(views.UpdateView):
    template_name = "hod/update_staff.html"
    model = Staff
    form_class = StaffForm
    success_url= reverse_lazy('hod:manage_staff')
#students
class StudentView(View):
        form_class = StudentForm
        initial = {'key': 'value'}
        template_name = 'hod/student.html'

        def get(self, request, *args, **kwargs):
            form = self.form_class(initial=self.initial)
            return render(request, self.template_name, {'form': form})

        def post(self, request, *args, **kwargs):
            form = self.form_class(request.POST)
            if form.is_valid():
                form.save()
                return render(request,'hod/student.html')

            return render(request, self.template_name, {'form': form})


#Delete student by HOD
class StudentDelete(views.DeleteView):
    model = Student
    template_name='hod/delete_student.html'
    success_url= reverse_lazy('hod:manage_student')

#Update staff
class StudentUpdate(views.UpdateView):
    template_name = "hod/update_student.html"
    model = Enroll
    form_class = EnrollForm
    success_url= reverse_lazy('hod:manage_student')

#entroll students
def enroll(request):
    submitted= False
    if request.method == 'POST':
        form=EnrollForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, "hod/enroll.html")

    else:
            form=EnrollForm
            if 'submitted' in request.GET:
                submitted= True
            return render(request, "hod/enroll.html",{'form':form,'submitted':submitted})

#LIST all the student
def manage_student(request):
    context ={}
    context["enroll"] = Enroll.objects.all()
    return render(request, "hod/manage_student.html",context)

student/views.py
from django.shortcuts import render, redirect
from .forms import StudentProfileForm

def student_home(request):
    return render(request,"student/home_content.html")

def student_profile(request):
    submitted= False
    if request.method == 'POST':
        form=StudentProfileForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request,"student/student_profile.html")

    else:
            form=StudentProfileForm
            if 'submitted' in request.GET:
                submitted= True
            return render(request, "student/student_profile.html",{'form':form,'submitted':submitted})
    
    
    
    

templates/hod/add_course.html
{% extends 'hod/base_template.html' %}
{% block main_content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                      <div class="card-header">
                        <h3 class="card-title">Add course</h3>
                      {% if submitted %}
                      Course Submitted Successfully
                      {% else %}
                      </div>
                      
                        </br>
                        </form>
                        <body>
                          <form role="form" action="add_course" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                        <!-- /.card-body -->
                        <div class="card-footer">
                          <button type="submit" class="btn btn-primary btn-block">Add Course</button>
                        </div>
                      </form>
                      {% endif %}
                    </div>
                    <!-- /.card -->
        
        
                    <!-- general form elements -->
  
                  </div>
            </div>
        </div>
    </section>
{% endblock main_content %}
      

templates/hod/add_department.html
{% extends 'hod/base_template.html' %}
{% block main_content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                      <div class="card-header">
                        <h3 class="card-title">Add Department</h3>
                      </div>
                      <!-- /.card-header -->
                      <!-- form start -->
                    </br>
                      <body>
                      <form role="form" action="add_department" method="post">
                        {% csrf_token %}
                        Department Name: <input type="text" name="name"/><br/>
                        <input type="submit" value="Post"/>
                      </form>
                      </body>
                    <!-- /.card -->
                    <!-- general form elements -->
                  </div>
            </div>
        </div>
    </section>
{% endblock main_content %}
      

templates/hod/add_student.html
{% extends 'hod/base_template.html' %}


{% block main_content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                      <div class="card-header">
                        <h3 class="card-title">Add student</h3>
                      </div>
                      <!-- /.card-header -->
                      <!-- form start -->
                      <form role="form" action="/add_student" method="post">
                       {% csrf_token %}
                        <div class="card-body">
                          <div class="form-group">
                            <label>Email address</label>
                            <input type="email" class="form-control" id="email" placeholder="Enter email">
                          </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" class="form-control" placeholder="Password" name="password">
                        </div>
                        <div class="form-group">
                            <label>First Name</label>
                            <input type="text" class="form-control"  placeholder="First Name" name="first_name">
                        </div>
                        <div class="form-group">
                            <label>Last Name</label>
                            <input type="text" class="form-control"  placeholder="last Name" name="last_name">
                        </div>
                        <div class="form-group">
                            <label>User Name</label>
                            <input type="text" class="form-control"  placeholder="user Name" name="user_name">
                        </div>
                        <div class="form-group">
                            <label>Address</label>
                            <input type="text" class="form-control"  placeholder="Address" name="Address">
                        </div>
                        <div class="form-group">
                            <label>Gender</label>
                             <select class="form-control" name="gender">
                                <option>Male</option>
                                <option>Female</option>
                                <option>LGBTQ</option>
                             </select>  
                        </div>   
                        <div class="form-group">
                        <label>Department</label>
                         <select class="form-control" name="course">
                            {% for department in department %}
                            <option>{{department.name}}</option>
                            {% endfor %}
                         </select>   
                        </div>
                         
                        <div class="form-group">
                            <label>Session Start</label>
                            <input type="date" class="form-control" placeholder="session Start year" name="session_start">
                        </div>
                        <div class="form-group">
                            <label>Session End</label>
                            <input type="date" class="form-control" placeholder="session End year" name="session_end">
                        </div>
                        <div class="form-group">
                          <label>ID proof</label>
                          <input type="file" class="form-control" placeholder="session End year" name="ID proof">
                      </div>
                      <div class="form-group">
                        <label>Profile image</label>
                        <input type="file" class="form-control" placeholder="session End year" name="Profile image">
                    </div>
                            <div class="form-group">
                          {% if messages %}
                          <div class="col-12">
                            {% for messages in messages %}
                            {% if messages.tags == 'error'%}
                            <div class="alert alert-danger" style="margin-top:10px">{{ messages }}</div>
                          </div>
                            {% endif %}
                            {% endfor %}
                          <!-- /.col -->
                        </div>
                          {% endif %}
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                          <button type="submit" class="btn btn-primary btn-block">Add Student</button>
                        </div>
                      </form>
                    </div>
                    <!-- /.card -->
        
                    <!-- general form elements -->
  
                  </div>
            </div>
        </div>
    </section>
{% endblock main_content %}
      

templates/hod/delete_course.html
{% extends 'hod/base_template.html' %}


{% block main_content %}


<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete?</p>
   
    <input type="submit" value="Confirm">
</form>
{% endblock main_content %}

templates/hod/delete_department.html
{% extends 'hod/base_template.html' %}


{% block main_content %}


<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete?</p>
   
    <input type="submit" value="Confirm">
</form>
{% endblock main_content %}

templates/hod/delete_staff.html
{% extends 'hod/base_template.html' %}


{% block main_content %}


<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete?</p>
   
    <input type="submit" value="Confirm">
</form>
{% endblock main_content %}

templates/hod/list_department.html
{% extends 'hod/base_template.html' %}
{% block main_content %}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <h3 class="card-title">Department Details</h3>
  
                  <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                      <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
  
                      <div class="input-group-append">
                        <button type="submit" class="btn btn-default">
                          <i class="fas fa-search"></i>
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                  <table class="table table-hover text-nowrap">
                    <thead>
                      <tr>
                        <th>Department Name</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for data in department %}.
                        <tr>
                          <td>{{ data.name }}</td>
                          
                          <td><a href="{% url 'hod:delete_department' data.id %}"  class ="btn btn-success">Delete</a> </td>
                        </tr>
                    
                     
                        {% endfor %}
                     
                      </div>
                    </tbody>
                  </table>
                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
            </div>
        </div>
    </div>
</section>
{% endblock main_content %}
  

                      
      

templates/hod/manage_staff.html
{% extends 'hod/base_template.html' %}
{% block main_content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                  <div class="card">
                    <div class="card-header">
                      <h3 class="card-title">Staff Details</h3>
      
                      <div class="card-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                          <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
      
                          <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                              <i class="fas fa-search"></i>
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                      <table class="table table-hover text-nowrap">
                        <thead>
                          <tr>
                            <th>Name</th>
                            <th>Department</th>
                            <th>Course</th>
                            <th>Designation</th>
                          </tr>
                        </thead>
                        <tbody>
                        {% for staff in staff %}
                          <tr>
                            <td>{{staff.user}}</td>
                            <td>{{staff.department}}</td>
                            <td>{{staff.course}}</td>
                            <td><span class="tag tag-success">faculty</span></td>
                            <td><a href="{% url 'hod:update_staff' staff.id %}" class ="btn btn-success">Edit</a> </td>
                            <td><a href="{% url 'hod:delete_staff' staff.id %}" class ="btn btn-success">Delete Staff</a> </td>
                          </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                    </div>
                    <!-- /.card-body -->
                  </div>
                  <!-- /.card -->
                </div>
            </div>
        </div>
    </section>
{% endblock main_content %}
      

templates/hod/manage_student.html
{% extends 'hod/base_template.html' %}
{% block main_content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                  <div class="card">
                    <div class="card-header">
                      <h3 class="card-title">Student Details</h3>
      
                      <div class="card-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                          <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
      
                          <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                              <i class="fas fa-search"></i>
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                      <table class="table table-hover text-nowrap">
                        <thead>
                          <tr>
                            <th>Name</th>
                            <th>Department</th>
                            <th>year</th    
                          </tr>
                        </thead>
                        <tbody>
                        {% for student in enroll %}
                            <tr>
                            <td>{{student.student}}</td>
                            <td>{{student.department}}</td>
                            <td>{{student.session_year }}</td>
                            <td><span class="tag tag-success">Student</span></td>
                            <td><a href="{% url 'hod:update_student' student.id %}" class ="btn btn-success">Edit</a> </td>
                            <td><a href="{% url 'hod:delete_student' student.id %}" class ="btn btn-success">Delete Student</a> </td>
                          </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                    </div>
                    <!-- /.card-body -->
                  </div>
                  <!-- /.card -->
                </div>
            </div>
        </div>
    </section>
{% endblock main_content %}
      

templates/hod/update_staff.html
{% extends 'hod/base_template.html' %}
{% block main_content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock main_content %}